---
title: "GMSP Indicators"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(rmarkdown)
library(flexdashboard)
library(tidyverse)
library(plotly)
library(ggplot2)

#data
cca_df <- data.frame (region  = c("MSP","MSP","MSP","MSP","MSP",
                                  "Chicago","Chicago","Chicago","Chicago","Chicago",
                                  "Boston","Boston","Boston","Boston","Boston",
                                  "Austin","Austin","Austin","Austin","Austin",
                                  "Pittsburgh","Pittsburgh","Pittsburgh","Pittsburgh","Pittsburgh"
),
Legend = c("MSP","MSP","MSP","MSP","MSP",
    "peer regions","peer regions","peer regions","peer regions","peer regions",
    "peer regions","peer regions","peer regions","peer regions","peer regions",
    "peer regions","peer regions","peer regions","peer regions","peer regions",
    "peer regions","peer regions","peer regions","peer regions","peer regions"
),
year = c(2019,2020,2021,2022,2023,
         2019,2020,2021,2022,2023,
         2019,2020,2021,2022,2023,
         2019,2020,2021,2022,2023,
         2019,2020,2021,2022,2023),
value = c(0.153,0.163,NA,0.186,0.161,
          0.25,0.26,0.29,0.28,0.26,
          0.11,0.13,NA,0.19,0.22,
          0.17,0.16,0.20,0.13,0.15,
          0.12,0.13,NA,0.18,0.16)
)

cca_df = cca_df %>%
  group_by(year) %>%
  mutate(RK = rank(desc(value),ties.method = "min"))

```


# Job Growth {data-navmenu="Economy"}


Row {data-width=150}
--------------------------------------
### Indicator
```{r}
valueBox(value = "Annual Job Growth",icon = NA,caption = "Indicator - Economy",color = "lightblue")
```

### Indicator
```{r}
valueBox(value = 37.7,icon = NA,caption = "MSP Region, 2023",color = "lightblue")
```

### Peer Comparison
```{r}
valueBox(value = "3rd Highest",icon = "fa-arrow-up",caption = "out of 12 regions", color = "white")
```

### MSP Trends
```{r}
valueBox(value = "Worsening",icon = "fa-arrow-down",caption = "MSP trend from 2021", color = "white")
```
Row {data-width=350}
-----------------------------------------------------------------------

### Peer Comparison Over Time

```{r}
x_lines = cca_df %>% 
  na.omit() %>%
  ggplot( aes(x=year, y=value, group=region, color = Legend)) +
  geom_line(aes(size=Legend)) + 
  geom_point(size = 1.8) + 
  scale_x_continuous(expand = c(0.04, 0), limits = c(2019, NA), 
                     breaks = seq(2019, 2023, 1)) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 0.35), 
                     breaks = seq(0.05, 0.5, 0.05)) +
  scale_color_manual(values=c(MSP='seagreen3', 'peer regions'='grey')) +
  scale_size_manual(values = c(MSP=1.2, no=0.8))+
  theme(
    text = element_text(family = "Lato")
  )

ggplotly(x_lines, tooltip = c("year", "region", "value"))

```

### Peer Comparison - 2023

```{r}
x_bar = cca_df %>%
  filter(year ==2023) %>%
  ggplot(aes(x=reorder(region, -RK), y=value, group=Legend, fill = Legend)) + 
  geom_bar(stat="identity")  + 
  scale_fill_manual(values=c("seagreen3","grey")) +
  coord_flip() +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 30)) +
  scale_y_continuous(labels = scales::percent, limits = c(0,0.4), breaks = seq(0,0.4,0.05))+
  xlab("") +
  ylab("Proportion (%) responding 'TRUE'") +
  theme(
    plot.background = element_rect(fill = "white"),
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(color = "grey"),
    panel.grid.minor = element_line(color = "grey"),
    axis.line.x = element_line(color = "grey"),
    plot.title=element_text(size=18, face = 'bold'),
    plot.subtitle=element_text(size=12, face = 'italic'),
    axis.title.y =element_text(size=12, face = 'italic', margin = margin(r = 10)),
    axis.text.x = element_text(size = 10, face = 'bold'),
    axis.text.y = element_text(size = 12, face = 'bold'),
    plot.margin = unit(c(1,1,1,1.5), "cm"),
    plot.caption = element_text(hjust = 0),
    text = element_text(family = "Lato")
  )

ggplotly(x_bar, tooltip = c("year", "region", "value"))
```


# Indicator #2 {data-navmenu="Economy"}


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

### Chart AA2

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```


# Indicator #3 {data-navmenu="Talent"}


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

### Chart AA2

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```


# Indicator #4 {data-navmenu="Talent"}


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

### Chart AA2

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

